services:
  impreza-db:
    image: postgres:16
    restart: always
    container_name: impreza-db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: impreza_db_password
      POSTGRES_USER: impreza_app
      POSTGRES_DB: impreza
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - impreza-net
    volumes:
     - ./pg-data:/var/lib/postgresql/data

volumes:
  pg-data:

networks:
  impreza-net:
    driver: bridge